version: '3.7' # 사용할 Docker Compose 파일 버전

services: # 컨테이너 서비스 정의
    django_gunicorn: # Django + Gunicorn 애플리케이션 서버
        container_name: django_gunicorn
        restart: always # 컨테이너가 죽으면 항상 재시작
        volumes:
            - static:/static # static 파일 저장소를 공유
        build:
            context: . # 현재 폴더(.)에 있는 Dockerfile을 빌드
        ports:
            - '8000:8000' # 로컬 포트 8000 ↔ 컨테이너 포트 8000 매핑
        depends_on:
            - mysql_server # MySQL 서버가 켜진 후에 Django 실행
        networks:
            - compose_net # 동일 네트워크(compose_net)로 연결 (MySQL, nginx와 통신 가능)

    nginx: # Nginx 웹 서버
        container_name: nginx
        build: ./nginx_server # nginx_server 폴더에 있는 Dockerfile을 빌드
        volumes:
            - static:/static # static 파일을 nginx가 읽을 수 있도록 연결
        ports:
            - '80:80' # 로컬 포트 80 ↔ 컨테이너 포트 80 매핑 (HTTP 기본 포트)
        depends_on:
            - django_gunicorn # Django 서버가 켜진 후에 Nginx를 실행
        networks:
            - compose_net # 동일 네트워크(compose_net)로 연결

volumes: # 영구 저장소 설정
    static: # Django static 파일 공유용 볼륨

networks: # 서비스끼리 통신할 수 있게 하는 가상 네트워크 설정
    compose_net:
        name: django_net # 네트워크 이름을 'django_net'으로 명시
        driver: bridge # 기본 브리지 네트워크 사용 (컨테이너 간 통신 가능)
